=== frosticecold/isep_lprog_17_18/2DC_1151708_1161386_1090657/xml/ADOTAPets.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema elementFormDefault="qualified" attributeFormDefault="unqualified" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.dei.isep.ipp.pt/lprog/adotapets">
	<xsd:element name="ADOTAPets">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Animais" type="TAnimais" maxOccurs="unbounded" />
				<xsd:element name="Boxes" type="TBoxes" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
		<xsd:keyref name="boxIDRef" refer="boxKey">
			<xsd:selector xpath="./Animais/Animal"/>
			<xsd:field xpath="@BoxID"/>
		</xsd:keyref>
		<xsd:key name="boxKey">
			<xsd:selector xpath="./Boxes/Box"/>
			<xsd:field xpath="@BoxID"/>
		</xsd:key>
	</xsd:element>
	<xsd:complexType name="TAnimais">
		<xsd:sequence>
			<xsd:element name="Animal" type="TAnimal" maxOccurs="unbounded" />
		</xsd:sequence>
		<xsd:attribute name="Tipo" type="xsd:string" fixed="Domesticos"/>
	</xsd:complexType>
	<xsd:complexType name="TBoxes">
		<xsd:sequence>
			<xsd:element name="Box" type="TBox" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TAnimal">
		<xsd:sequence>
			<xsd:element name="Nome" type="TText" />
			<xsd:element name="Raca" type="TText" />
			<xsd:element name="Idade" type="TIdade" />
			<xsd:element name="Sexo" type="TSexo" />
			<xsd:element name="Peso" type="TPeso" />
			<xsd:element name="Personalidade" type="TText" />
			<xsd:element name="Vacinas" type="TVacinas"/>
			<xsd:element name="Racao" type="TRacao"/>
			<xsd:element name="ExercicioFisico" type="TExercicioFisico"/>
		</xsd:sequence>
		<xsd:attribute name="TipoAnimal" type="TTipoAnimal" default="Outro"/>
		<xsd:attribute name="BoxID" type="xsd:integer" use="required"/>
		<xsd:attribute name="Chip">
			<xsd:simpleType>
				<xsd:restriction base = "xsd:string">
					<xsd:pattern value ="PT-[0-9]{5}"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:complexType name="TBox">
		<xsd:attribute name="BoxID">
			<xsd:simpleType>
				<xsd:restriction base = "xsd:integer">
					<xsd:minInclusive value = "1"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
	</xsd:complexType>
	<xsd:simpleType name="TTipoAnimal">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="cão"/>
			<xsd:enumeration value="gato"/>
			<xsd:enumeration value="outro"/>
			<xsd:enumeration value="Cão"/>
			<xsd:enumeration value="Gato"/>
			<xsd:enumeration value="Outro"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TRacao">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="normal"/>
			<xsd:enumeration value="light"/>
			<xsd:enumeration value="sénior"/>
			<xsd:enumeration value="Normal"/>
			<xsd:enumeration value="Light"/>
			<xsd:enumeration value="Sénior"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TExercicioFisico">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="normal"/>
			<xsd:enumeration value="moderada"/>
			<xsd:enumeration value="grande"/>
			<xsd:enumeration value="Normal"/>
			<xsd:enumeration value="Moderada"/>
			<xsd:enumeration value="Grande"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="TVacinas">
		<xsd:sequence>
			<xsd:element name="Vacina" type="TVacina" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="TVacina">
		<xsd:sequence>
			<xsd:element name="DataAdministracao" type="xsd:date"/>
			<xsd:element name="Validade" type="TValidade"/>
		</xsd:sequence>
		<xsd:attribute name="Nome" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:simpleType name="TValidade">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Anual"/>
			<xsd:enumeration value="anual"/>
			<xsd:enumeration value="Mensal"/>
			<xsd:enumeration value="mensal"/>
			<xsd:enumeration value="Sem Validade"/>
			<xsd:enumeration value="Sem validade"/>
			<xsd:enumeration value="sem validade"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TText">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[a-zA-Z]+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TIdade">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="30"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TSexo">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Masculino"/>
			<xsd:enumeration value="Feminino"/>
			<xsd:enumeration value="masculino"/>
			<xsd:enumeration value="feminino"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TPeso">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[0-2]?[0-9].[0-9][0-9]Kg"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== frosticecold/isep_lprog_17_18/2DC_1151708_1161386_1090657/xml2html/t1/ADOTAPets.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="ADOTAPets.xsl"?>
<ADOTAPets 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.dei.isep.ipp.pt/lprog/adotapets ADOTAPets.xsd" 
    xmlns="http://www.dei.isep.ipp.pt/lprog/adotapets">
    <?xml-stylesheet type="text/xsl" href="adotapets.xsl"?>
    <Animais>
        <Animal TipoAnimal="Cão" BoxID="1" Chip="PT-12345">
            <Nome>Lassie</Nome>
            <Raca>Collie</Raca>
            <Idade>8</Idade>
            <Sexo>Feminino</Sexo>
            <Peso>15.01Kg</Peso>
            <Personalidade>Divertido</Personalidade>
            <Vacinas>
                <Vacina Nome="Contra Pulgas">
                    <DataAdministracao>2018-05-03</DataAdministracao>
                    <Validade>mensal</Validade>
                </Vacina>
                <Vacina Nome="Antirrábica">
                    <DataAdministracao>2018-07-03</DataAdministracao>
                    <Validade>Sem Validade</Validade>
                </Vacina>
                <Vacina Nome="Giardíase">
                    <DataAdministracao>2019-05-27</DataAdministracao>
                    <Validade>Anual</Validade>
                </Vacina>
                <Vacina Nome="Óctupla">
                    <DataAdministracao>2018-05-03</DataAdministracao>
                    <Validade>Mensal</Validade>
                </Vacina>
            </Vacinas>
            <Racao>Light</Racao>
            <ExercicioFisico>Normal</ExercicioFisico>
        </Animal>
        <Animal TipoAnimal="Gato" BoxID="2">
            <Nome>Vistoso</Nome>
            <Raca>Rafeiro</Raca>
            <Idade>2</Idade>
            <Sexo>Masculino</Sexo>
            <Peso>6.01Kg</Peso>
            <Personalidade>Rabujento</Personalidade>
            <Vacinas>
                <Vacina Nome="Contra Pulgas">
                    <DataAdministracao>2018-05-03</DataAdministracao>
                    <Validade>mensal</Validade>
                </Vacina>
                <Vacina Nome="Antirrábica">
                    <DataAdministracao>2018-07-03</DataAdministracao>
                    <Validade>Sem Validade</Validade>
                </Vacina>
                <Vacina Nome="Giardíase">
                    <DataAdministracao>2019-05-27</DataAdministracao>
                    <Validade>Anual</Validade>
                </Vacina>
                <Vacina Nome="Óctupla">
                    <DataAdministracao>2018-05-03</DataAdministracao>
                    <Validade>Mensal</Validade>
                </Vacina>
            </Vacinas>
            <Racao>Light</Racao>
            <ExercicioFisico>Normal</ExercicioFisico>
        </Animal>
        <Animal TipoAnimal="gato" BoxID="3">
            <Nome>Tareco</Nome>
            <Raca>Collie</Raca>
            <Idade>8</Idade>
            <Sexo>Feminino</Sexo>
            <Peso>15.01Kg</Peso>
            <Personalidade>Divertido</Personalidade>
            <Vacinas>
                <Vacina Nome="Contra Pulgas">
                    <DataAdministracao>2018-05-03</DataAdministracao>
                    <Validade>mensal</Validade>
                </Vacina>
                <Vacina Nome="Antirrábica">
                    <DataAdministracao>2018-07-03</DataAdministracao>
                    <Validade>Sem Validade</Validade>
                </Vacina>
                <Vacina Nome="Giardíase">
                    <DataAdministracao>2019-05-27</DataAdministracao>
                    <Validade>Anual</Validade>
                </Vacina>
                <Vacina Nome="Óctupla">
                    <DataAdministracao>2018-05-03</DataAdministracao>
                    <Validade>Mensal</Validade>
                </Vacina>
            </Vacinas>
            <Racao>Light</Racao>
            <ExercicioFisico>Normal</ExercicioFisico>
        </Animal>
        <Animal TipoAnimal="Outro" BoxID="5">
            <Nome>Indefinido</Nome>
            <Raca>Collie</Raca>
            <Idade>8</Idade>
            <Sexo>Feminino</Sexo>
            <Peso>15.01Kg</Peso>
            <Personalidade>Divertido</Personalidade>
            <Vacinas>
                <Vacina Nome="Contra Pulgas">
                    <DataAdministracao>2018-05-03</DataAdministracao>
                    <Validade>mensal</Validade>
                </Vacina>
                <Vacina Nome="Antirrábica">
                    <DataAdministracao>2018-07-03</DataAdministracao>
                    <Validade>Sem Validade</Validade>
                </Vacina>
                <Vacina Nome="Giardíase">
                    <DataAdministracao>2019-05-27</DataAdministracao>
                    <Validade>Anual</Validade>
                </Vacina>
                <Vacina Nome="Óctupla">
                    <DataAdministracao>2018-05-03</DataAdministracao>
                    <Validade>Mensal</Validade>
                </Vacina>
            </Vacinas>
            <Racao>Light</Racao>
            <ExercicioFisico>Normal</ExercicioFisico>
        </Animal>
    </Animais>
    <Boxes>
        <Box BoxID="1"/>
        <Box BoxID="2"/>
        <Box BoxID="3"/>
        <Box BoxID="4"/>
        <Box BoxID="5"/>
    </Boxes>
</ADOTAPets>
